import { Devotional, Translation } from './types';

export const CONTENT: Record<'tl' | 'en', Translation> = {
  tl: {
    nav: {
      home: 'Home',
      about: 'Tungkol Sa Amin',
      devotionals: 'Mga Debosyon',
      joinLive: 'Sumali Live',
      getInvolved: 'Sumali sa Paglilingkod',
    },
    home: {
      hero: {
        title: 'Bumangon Nang Maaga.\nSimulan ang Araw Kasama ang Diyos.\nSama-sama.',
        subtitle: 'Ang Rise Up Challenge ay isang pandaigdigang komunidad ng mga alagad na araw-araw na nagsasama-sama para sa tahimik na oras at debosyon sa umaga.',
        ctaJoin: 'Sumali sa Susunod na Debosyon',
        ctaWatch: 'Panoorin ang mga Nakaraan',
      },
      started: {
        title: 'Paano Nagsimula',
        body: 'Nagsimula ang Rise Up Challenge noong panahon ng COVID-19 lockdowns, nang ang isang maliit na grupo ng mga alagad ay nagpasya na bumangon nang maaga at hanapin ang Diyos nang sama-sama online. Kahit matapos ang lockdowns, nagpatuloy ang mga debosyon.',
      },
      whatWeDo: {
        title: 'Ang Ginagawa Namin',
        daily: 'Araw-araw na Debosyon sa Umaga',
        dailyDesc: 'Panalangin online at pagninilay sa Kasulatan tuwing umaga.',
        ledBy: 'Pinangungunahan ng mga Alagad sa Buong Mundo',
        ledByDesc: 'Mga tagapagsalita mula sa iba’t ibang bansa at simbahan.',
        accessible: 'Maaaring Balikan Kahit Kailan',
        accessibleDesc: 'Ang mga sesyon ay naka-record para mapanood sa ibang oras.',
      },
      scripture: {
        text: '“Sa kinaumagahan, Panginoon, aking maririnig ang aking tinig.”',
        ref: '— Awit 5:3',
      },
    },
    about: {
      title: 'Tungkol sa Rise Up Challenge',
      intro: 'Ang Rise Up Challenge ay isang boluntaryong ministeryo ng debosyon na binuo ng mga miyembro ng International Churches of Christ. Layunin naming hikayatin ang mga alagad na unahin ang Diyos araw-araw.',
      missionTitle: 'Misyon',
      mission: 'Hikayatin ang mga alagad na unahin ang Diyos araw-araw.',
      visionTitle: 'Bisyon',
      vision: 'Isang pandaigdigang komunidad na matatag sa pananampalataya.',
    },
    devotionals: {
      title: 'Mga Debosyon',
      intro: 'Hindi naka-attend ng live? Maaari mong panoorin ang mga nakaraang debosyon dito.',
      filterAll: 'Lahat',
      filterEn: 'Ingles',
      filterTl: 'Tagalog',
      searchPlaceholder: 'Maghanap ayon sa pamagat o tagapagsalita...',
      watchBtn: 'Panoorin',
    },
    joinLive: {
      title: 'Sumali Live',
      intro: 'Araw-araw kaming nagtitipon online para sa debosyon sa umaga. Lahat ay malugod na inaanyayahan.',
      platform: 'Platform: Zoom',
      language: 'Wika: Pangunahing Tagalog, paminsan-minsan ay Ingles',
      schedule: 'Oras: 5:30 AM (Manila Time)',
      btn: 'Buksan ang Zoom',
    },
    getInvolved: {
      title: 'Sumali sa Paglilingkod',
      lead: 'Manguna sa Debosyon',
      leadDesc: 'Ibahagi ang iyong pananampalataya at manguna sa isang umagang debosyon.',
      help: 'Tumulong sa Hosting',
      helpDesc: 'Tumulong sa pamamahala ng Zoom room o pag-record ng session.',
      connect: 'Manatiling Konektado',
      connectDesc: 'Sumali sa aming Facebook group para sa mga updates.',
    },
    footer: {
      copyright: '© 2024 Rise Up Challenge. All rights reserved.',
    },
  },
  en: {
    nav: {
      home: 'Home',
      about: 'About',
      devotionals: 'Devotionals',
      joinLive: 'Join Live',
      getInvolved: 'Get Involved',
    },
    home: {
      hero: {
        title: 'Rise Up Early.\nStart Your Day with God.\nTogether.',
        subtitle: 'Rise Up Challenge is a global community of disciples who gather daily for quiet time and morning devotionals — united by faith, wherever we are in the world.',
        ctaJoin: 'Join the Next Devotional',
        ctaWatch: 'Watch Past Devotionals',
      },
      started: {
        title: 'How It Started',
        body: 'Rise Up Challenge began during the COVID-19 lockdowns, when a small group of disciples made a commitment to rise early and seek God together online. Even after lockdowns ended, the devotionals continued.',
      },
      whatWeDo: {
        title: 'What We Do',
        daily: 'Daily Morning Devotionals',
        dailyDesc: 'Online prayer and Scripture reflection every morning.',
        ledBy: 'Led by Disciples Worldwide',
        ledByDesc: 'Speakers from different countries and churches.',
        accessible: 'Accessible Anytime',
        accessibleDesc: 'Sessions are recorded for later viewing.',
      },
      scripture: {
        text: '“In the morning, Lord, you hear my voice.”',
        ref: '— Psalm 5:3',
      },
    },
    about: {
      title: 'About Rise Up Challenge',
      intro: 'Rise Up Challenge is a volunteer-led devotional ministry created by members of the International Churches of Christ. Our mission is to encourage disciples to consistently seek God first every day.',
      missionTitle: 'Mission',
      mission: 'To encourage disciples to seek God first every day.',
      visionTitle: 'Vision',
      vision: 'A spiritually strong and connected global community.',
    },
    devotionals: {
      title: 'Devotionals Repository',
      intro: 'Missed a live devotional? You can watch or listen to past devotionals here.',
      filterAll: 'All',
      filterEn: 'English',
      filterTl: 'Tagalog',
      searchPlaceholder: 'Search by title or speaker...',
      watchBtn: 'Watch Now',
    },
    joinLive: {
      title: 'Join Live',
      intro: 'We gather online every day for a morning devotional. Everyone is welcome.',
      platform: 'Platform: Zoom',
      language: 'Language: Primarily Tagalog, occasional English',
      schedule: 'Time: 5:30 AM (Manila Time)',
      btn: 'Launch Zoom',
    },
    getInvolved: {
      title: 'Get Involved',
      lead: 'Lead a Devotional',
      leadDesc: 'Share your faith and lead a morning session.',
      help: 'Help with Hosting',
      helpDesc: 'Assist with managing the Zoom room or recording sessions.',
      connect: 'Stay Connected',
      connectDesc: 'Join our Facebook group for updates and community.',
    },
    footer: {
      copyright: '© 2024 Rise Up Challenge. All rights reserved.',
    },
  },
};

export const MOCK_DEVOTIONALS: Devotional[] = [
  {
    id: '1',
    date: '2024-05-20',
    title: 'Faith in the Storm',
    speaker: 'Juan dela Cruz',
    language: 'tl',
    scripture: 'Mark 4:35-41',
    videoUrl: '#',
    thumbnailUrl: 'https://picsum.photos/id/1018/400/225',
  },
  {
    id: '2',
    date: '2024-05-19',
    title: 'The Power of Humility',
    speaker: 'Maria Santos',
    language: 'tl',
    scripture: 'Philippians 2:3-4',
    videoUrl: '#',
    thumbnailUrl: 'https://picsum.photos/id/1015/400/225',
  },
  {
    id: '3',
    date: '2024-05-18',
    title: 'Walking with God',
    speaker: 'John Smith',
    language: 'en',
    scripture: 'Micah 6:8',
    videoUrl: '#',
    thumbnailUrl: 'https://picsum.photos/id/1016/400/225',
  },
  {
    id: '4',
    date: '2024-05-17',
    title: 'Ang Pag-ibig ng Ama',
    speaker: 'Pedro Penduko',
    language: 'tl',
    scripture: 'Luke 15:11-32',
    videoUrl: '#',
    thumbnailUrl: 'https://picsum.photos/id/1025/400/225',
  },
  {
    id: '5',
    date: '2024-05-16',
    title: 'Morning Mercies',
    speaker: 'Sarah Johnson',
    language: 'en',
    scripture: 'Lamentations 3:22-23',
    videoUrl: '#',
    thumbnailUrl: 'https://picsum.photos/id/1036/400/225',
  },
  {
    id: '6',
    date: '2024-05-15',
    title: 'Pananatili sa Puno',
    speaker: 'Mateo Reyes',
    language: 'tl',
    scripture: 'John 15:5',
    videoUrl: '#',
    thumbnailUrl: 'https://picsum.photos/id/1043/400/225',
  },
];
